package:
  name: sidecar-search
  version: "0.2.1"

source:
  path: ../

build:
  noarch: python
  script: pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - sidecar-search = sidecar_search.cli:main

requirements:
  build:
    - python
    - pip
    - hatchling
  run:
    - python
    - pytorch ~=2.6
    - sentence-transformers ~=3.4
    - tqdm
    - numpy >=1.26.4
    - pyarrow
    - faiss-gpu ~=1.9.0
    - datasets >=3.3.2

test:
  imports:
    - sidecar_search
  requires:
    - pip
  commands:
    - pip check
    - sidecar-search init --help
    - sidecar-search build --help
    - sidecar-search dump --help
    - sidecar-search index --help

about:
  home: https://github.com/colonelwatch/sidecar-search
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Build tools for sidecar indices to add sematic search to anything
  dev_url: https://github.com/colonelwatch/sidecar-search
