default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        description: Run the Ruff linter
        entry: ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff format
        description: Run the Ruff formatter
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: pyrefly-check
        name: pyrefly check
        description: Run the Pyrefly type checker
        entry: pyrefly check
        language: system
        types_or: [python, pyi]
        pass_filenames: false
      - id: pytest
        name: pytest
        description: Run unit tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
